feat: add lockImages (#85897)

diff --git a/ci-job-template.yml b/ci-job-template.yml
--- a/ci-job-template.yml
+++ b/ci-job-template.yml
@@ -65,12 +65,17 @@ parameters:
   type: string
   default: 'pwa-nginx'
 
+  # Enable immutable images when created for Git tags.
+- name: lockImages
+  type: boolean
+  default: true
+  
   # Specifies the maximum job execution time in minutes.
 - name: jobTimeoutInMinutes
   type: number
   default: 300
 
-  # Specifies whether future jobs should run even if this job fails; defaults to 'false'.
+  # Specifies whether future jobs should run even if this job fails.
 - name: jobContinueOnError
   type: boolean
   default: false
@@ -141,6 +146,7 @@ jobs:
               jobTimeoutInMinutes:            ${{ parameters.jobTimeoutInMinutes }}
               predefinedImageTag:             ${{ parameters.predefinedImageTag }}
               predefinedImageName:            ${{ parameters.predefinedImageName }}
+              lockImages:                     ${{ parameters.lockImages }}
           EOF
 
     - task: Bash@3
@@ -176,6 +182,7 @@ jobs:
           elif [[ $(Build.SourceBranch) =~ tags/(.*) ]]; then
             DEFINED_TAG="${BASH_REMATCH[1]}"
             # Pattern to remove invalid characters
+            # See: https://docs.docker.com/engine/reference/commandline/tag/
             pattern="[^a-zA-Z0-9_\.\\-]"
             DEFINED_TAG=$(echo "${DEFINED_TAG}" | sed "s/$pattern//g")
           # If neither a PREDEFINED_TAG is set nor it is a tagged build, use the build id as tag
@@ -393,7 +400,41 @@ jobs:
               nginx-image:                           ${REGISTRY}/${IMAGE_NGINX}:${TAG}
               
           EOF
+      
+    # If the parameter lockImages is true and the Build.SourceBranch is a tag, 
+    # then the generated Docker images in the ACR will be made non-overwritable and non-deletable.
+    - task: AzureCLI@2
+      timeoutInMinutes: 5
+      condition: and(succeeded(), eq('${{ parameters.lockImages }}', true), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
+      displayName: "Set image attributes"
+      env:
+        TAG: $(tag)
+        IMAGE_NAME_NGINX: $(imageNameNginx)
+        IMAGE_NAME_SSR: $(imageNameSSR)
+        REGISTRY: ${{ parameters.registry }}
+      inputs:
+        azureSubscription: '$(REPO_SERVICE_CONNECTION_ARM)'
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
 
+          #!/bin/bash
+          set -e
+
+          # Update the ssr image
+          az acr repository update \
+            --name "${REGISTRY}" \
+            --image "${IMAGE_NAME_SSR}:${TAG}" \
+            --delete-enabled false \
+            --write-enabled false
+           
+          # Update the nginx image
+          az acr repository update \
+            --name "${REGISTRY}" \
+            --image "${IMAGE_NAME_NGINX}:${TAG}" \
+            --delete-enabled false \
+            --write-enabled false
+          
     - task: Bash@3
       timeoutInMinutes: 5
       condition: always()
